export const BAIRROS = [
    { slug: "batel", nome: "Batel" },
    { slug: "agua-verde", nome: "Água Verde" },
    { slug: "portao", nome: "Portão" },
    { slug: "centro", nome: "Centro" },
    { slug: "cajuru", nome: "Cajuru" },
    { slug: "pinheirinho", nome: "Pinheirinho" },
    { slug: "boa-vista", nome: "Boa Vista" },
    { slug: "santa-felicidade", nome: "Santa Felicidade" },
    { slug: "bigorrilho", nome: "Bigorrilho" },
    { slug: "juveve", nome: "Juvevê" },
    { slug: "cabral", nome: "Cabral" },
    { slug: "hauer", nome: "Hauer" },
    { slug: "uberaba", nome: "Uberaba" },
    { slug: "xaxim", nome: "Xaxim" },
    { slug: "boqueirao", nome: "Boqueirão" },
    { slug: "tingui", nome: "Tingui" },
    { slug: "atuba", nome: "Atuba" },
    { slug: "bacacheri", nome: "Bacacheri" },
    { slug: "sao-lourenco", nome: "São Lourenço" },
    { slug: "cristo-rei", nome: "Cristo Rei" },
    { slug: "jardim-social", nome: "Jardim Social" },
    { slug: "alto-da-xv", nome: "Alto da XV" },
    { slug: "merces", nome: "Mercês" },
    { slug: "seminario", nome: "Seminário" },
    { slug: "vila-izabel", nome: "Vila Izabel" }
];
